### ISSUE TITLE
Pebble.add_layer has a poor exception type

### ISSUE THREAD

**Issue by jameinel** [canonical/operator#514]
If you try to call `add_layer('foo',...)` two times, (with the default `combine=False`), you get an HTTP Exception:
400 Bad Request: layer "hello" already exists

While this is a reasonable error message, it isn't a good *type* that a charm developer should be exposed to. (It makes it weird to try and write a testing layer that mimics the underlying Pebble behavior)

**Comment by jameinel** [comment]
It may be that we just start by translating all of the HTTP Errors from Pebble back into a ModelError (at the least it should be a subclass of that type).

**Comment by jameinel** [comment]
Another poor exception:
```
$ PYTHONPATH=. python3 ./test/pebble_cli.py add --combine hello hello2.layer
500 Internal Server Error: layer "hello" must define 'override' for service "serv"
```

That should certainly not be a 500 ISE, and should really be something like a ModelError.

**Comment by jnsgruk** [comment]
Does make me wonder if we should have a few specific exception types for Pebble errors; another similar case is if you try to start a service that's already started with Pebble - might be nice to be able to handle some of these specific cases without having to parse the message string in a ModelError I think?

**Comment by jameinel** [comment]
Yes, I do think we should have specialized errors for it, but mostly I
wanted to at least get us away from HTTP errors.

Also note that the quoting is weird:
```
500 Internal Server Error: layer "hello" must define 'override' for service
"serv"
```

Two strings are "" quoted, and one is '' quoted.

**Comment by benhoyt** [comment]
A couple of things here:

1) Yeah, it definitely shouldn't return 500 in this case -- thanks. Fixed in https://github.com/canonical/pebble/pull/36 (along with the inconsistent quoting fix).
2) As far as the Operator Framework side goes: this isn't actually a bare HTTP 400 error. It's a `pebble.APIError` (the underlying `urllib.error.HTTPError` is caught and re-raised as a `pebble.APIError` with helpful information in attributes). Do we need anything more than that? Why would it help to do a further transformation to a `ModelError`? So make take is, after the Pebble fix, we don't need to do anything further here. See also [a small tweak](https://github.com/canonical/operator/pull/523) in `pebble_cli.py` to make explicit that this is an `APIError`, not a raw `HTTPError`.

**Comment by jameinel** [comment]
pebble.APIError still doesn't quite seem like quite the right type. We are getting a LayerAlreadyExists error, vs something that could be a  MalformedRequestError, or an InternalServiceError or BadCredentialError, etc.

It is certainly better than HTTPError, and maybe in the end it doesn't really matter for charms as they won't really be catching it and recovering, as long as the end user / charm developer gets a clear message as to what is wrong so they can fix the charm.

**Comment by benhoyt** [comment]
Ah, I see what you're suggesting. Yeah, we could have specified error `kind` values like `layer-already-exists` from Pebble (currently these don't have `kind` set) turned into specific Python exceptions.

However, I think you're right that it's not worth it. It's a fair bit of busy work on both the Pebble and Operator Framework ends for a bunch of exception types that are probably never going to be explicitly used. We *want* these formatting type errors to bubble up and fail hard. I suggest with the 500 to 400 Pebble fix in place, we close this one now.

**Comment by benhoyt** [comment]
Closing per above.
